-- =============================================================
--  Tournament Tracker — Données
-- =============================================================
--  À exécuter APRÈS schema.sql.
--
--  Note sur l'écriture des paires : chaque joueur est désigné par son
--  nom, via une sous-requête, et non par un identifiant numérique en
--  dur. C'est volontaire. Des identifiants écrits en dur (1, 2, 3...)
--  ne sont corrects que si les joueurs ont été insérés exactement dans
--  le même ordre ; ajouter un seul joueur en amont décale tout et
--  fausse silencieusement les paires. Désigner les joueurs par leur
--  nom rend le fichier robuste à toute modification de l'ordre
--  d'insertion.
-- =============================================================

USE tournament_tracker;

-- -------------------------------------------------------------
--  Joueurs (228)
-- -------------------------------------------------------------
INSERT INTO players (first_name, last_name) VALUES
  ('Orest', 'Hura'),
  ('Valerii', 'Vlasenko'),
  ('Oleh', 'Napirko'),
  ('Mykyta', 'Smyrnov'),
  ('Nazarii', 'Kovalchuk'),
  ('Anton', 'Shypilov'),
  ('Roman', 'Reznychenko'),
  ('Oleksandr', 'Tuzhylin'),
  ('Roman', 'Cherevko'),
  ('Valerii', 'Melnyk'),
  ('Yevhen', 'Masko'),
  ('Yevhen', 'Pysmennyi'),
  ('Tomas', 'Hucko'),
  ('Premysl', 'Rucky'),
  ('Serhii', 'Prus'),
  ('Denys', 'Maltsev'),
  ('Ivan', 'Fashchevskyi'),
  ('Oleh', 'Savenkov'),
  ('David', 'Sabuka'),
  ('Karel', 'Farsky'),
  ('Dmytro', 'Patalakha'),
  ('Oleksandr', 'Tymofeev'),
  ('Evhenii', 'Hrytsenko'),
  ('Oleh', 'Kuzyshyn'),
  ('Serhii', 'Aristarkhov'),
  ('Volodymyr', 'Tatarnykov'),
  ('Oleksii', 'Tiutiunnyk'),
  ('Serhii', 'Kiilo'),
  ('Roman', 'Merkl'),
  ('Oleh', 'Varlamov'),
  ('Volodymyr', 'Bilobrov'),
  ('Bogdan', 'Panchenko'),
  ('Dmytro', 'Prylepa'),
  ('Dmytro', 'Belanchik'),
  ('Andrii', 'Dekhtiarenko'),
  ('Milan', 'Cuba'),
  ('Martin', 'Holub'),
  ('Oleksandr', 'Zhyrnov'),
  ('Yaroslav', 'Kovshun'),
  ('Stepan', 'Kalensky'),
  ('Marian', 'Melisek'),
  ('Oleh', 'Kurylenko'),
  ('Eduard', 'Populovskyi'),
  ('Serhii', 'Kushnirenko'),
  ('Dmytro', 'Palii'),
  ('Marcel', 'Cmil'),
  ('Vaclav', 'Coubal'),
  ('Josef', 'Chalupa'),
  ('Stepan', 'Rejent'),
  ('Tomas', 'Liska'),
  ('Lukas', 'Rulc'),
  ('Vadym', 'Kucheriavyi'),
  ('Andrii', 'Kurtenko'),
  ('Yevhen', 'Skorobahatyi'),
  ('Anatolii', 'Nazarov'),
  ('Bohdan', 'Kohut'),
  ('Ivan', 'Kozachuk'),
  ('Ihor', 'Serdiuk'),
  ('Roman', 'Boklah'),
  ('Sergey', 'Osipov'),
  ('Stanislav', 'Kucera'),
  ('Jan', 'Krojidlo'),
  ('Ondrej', 'Chadima'),
  ('Jachym', 'Juppa'),
  ('Oleh', 'Bandurka'),
  ('Serhii', 'Rak'),
  ('Vitalii', 'Ananiev'),
  ('Vitalii', 'Klymenko'),
  ('Radek', 'Slunecko'),
  ('Daniil', 'Yevdokymov'),
  ('Maksym', 'Tkalich'),
  ('Serhii', 'Danylov'),
  ('Mykola', 'Pohorilyi'),
  ('Ivan', 'Krivoy'),
  ('Mykolay', 'Treschetka'),
  ('Kostiantyn', 'Hrynenko'),
  ('Yan', 'Krol'),
  ('Maxim', 'Marchuk'),
  ('Jan', 'Marhol'),
  ('Jakub', 'Senk'),
  ('Michal', 'Makara'),
  ('Vladyslav', 'Kovalchuk'),
  ('Yaroslav', 'Vorsulyak'),
  ('Maksym', 'Khomenko'),
  ('Dmytro', 'Shchegelskyi'),
  ('Volodymyr', 'Ivasiv'),
  ('Mykola', 'Kulynych'),
  ('Oleh', 'Maksymkiv'),
  ('Vasyl', 'Salivonchyk'),
  ('Oleksandr', 'Maslovskyi'),
  ('Serhii', 'Priadko'),
  ('Ihor', 'Torhachov'),
  ('Petr', 'Abraham'),
  ('Martin', 'Stehlik'),
  ('Viktor', 'Kucala'),
  ('Petr', 'Fiser'),
  ('Jan', 'Seeman'),
  ('Josef', 'Hanacek'),
  ('Karel', 'Polak'),
  ('Artem', 'Chepurnyi'),
  ('Oleksandr', 'Mishchenko'),
  ('Serhii', 'Chelpanov'),
  ('Yevhen', 'Kryvorotko'),
  ('Zdenek', 'Sedivy'),
  ('Ladislav', 'Dobias'),
  ('Zdenek', 'Kuksa'),
  ('Anatolii', 'Nikolenko'),
  ('Vasyl', 'Verbianyi'),
  ('Roman', 'Zholubak'),
  ('Maksym', 'Mrykh'),
  ('Volodymyr', 'Voronenkov'),
  ('Serhii', 'Chuhai'),
  ('Maksym', 'Hubenko'),
  ('Andrii', 'Vasylets'),
  ('Artem', 'Yurkov'),
  ('Vladyslav', 'Mishchenko'),
  ('Oleksandr', 'Kolbasenko'),
  ('Jan Sr', 'Krames'),
  ('Mariia', 'Dotsenko'),
  ('Andrii', 'Derevianko'),
  ('Valerii', 'Merzlikin'),
  ('Dmytro', 'Novik'),
  ('Oleksandr', 'Levytskyi'),
  ('Jan', 'Blazek'),
  ('Roman', 'Matveichuk'),
  ('Vitalii', 'Kaganovych'),
  ('Vladyslav', 'Kovalenko'),
  ('Serhii', 'Honcharenko'),
  ('Vasyl', 'Matviichuk'),
  ('Viktor', 'Kodola'),
  ('Vadym', 'Ishchuk'),
  ('Yevhen', 'Bielokon'),
  ('Viktor', 'Sharpai'),
  ('Yaroslav', 'Stepanchuk'),
  ('Mykola', 'Polysynskyi'),
  ('Serhii', 'Kalenyk'),
  ('Serhii', 'Khandetskyi'),
  ('Nazar', 'Danyliuk'),
  ('Vadym', 'Hryban'),
  ('Vladyslav', 'Stukalov'),
  ('Vitalii', 'Korniichuk'),
  ('Andrii', 'Troian'),
  ('Evhenii', 'Holoborodko'),
  ('Pavel', 'Sourek'),
  ('Filip', 'Vesely'),
  ('Hryhorii', 'Prokopenko'),
  ('Oleh', 'Volynets'),
  ('Yurii', 'Volkov'),
  ('Ondrej', 'Mezera'),
  ('Volodymyr', 'Savoliuk'),
  ('Daniil', 'Habrelyan'),
  ('Roman', 'Sveshnykov'),
  ('Viktor', 'Hyriavyi'),
  ('Oleksandr', 'Syksa'),
  ('Oleksandr', 'Badanin'),
  ('Martin', 'Vorel'),
  ('Josef', 'Hondlik'),
  ('Ladislav', 'Hendrych'),
  ('Anton', 'Molochko'),
  ('Arsenii', 'Lobanov'),
  ('Oleksandr', 'Shyshman'),
  ('Oleh', 'Miklukha'),
  ('Ondrej', 'Karpisek'),
  ('Maksym', 'Studinikin'),
  ('Vsevolod', 'Kheresko'),
  ('Volodymyr', 'Dobrovolskyi'),
  ('Denys', 'Kozoriz'),
  ('Andrii', 'Homylko'),
  ('Ludek', 'Stoces'),
  ('Martin', 'Skyba'),
  ('Oleksandr', 'Mytsyk'),
  ('Serhii', 'Kryvoshyi'),
  ('Radovan', 'Pisa'),
  ('Sergii', 'Skhabitskiy'),
  ('Artur', 'Akopyan'),
  ('Jaroslav', 'Puk'),
  ('Petr', 'Kotrbacek'),
  ('Oleh', 'Plyska'),
  ('Dominik', 'Horak'),
  ('Pavel', 'Fencl'),
  ('Marek', 'Vyskocil'),
  ('Oleksandr', 'Ziakun'),
  ('Vihen', 'Saakian'),
  ('Maksym', 'Tiutiunnyk'),
  ('Ihor', 'Burak'),
  ('Yurii', 'Zvolynskyi'),
  ('Ivan', 'Nitchenko'),
  ('Andriy', 'Didyk'),
  ('Andrii', 'Kotiash'),
  ('Vasyl', 'Kondratenko'),
  ('Roman', 'Mazur'),
  ('Oleksandr', 'Lipeiko'),
  ('Vladimir', 'Lopata'),
  ('Tomas', 'Hanke'),
  ('Marek', 'Cizek'),
  ('Pavlo', 'Babenko'),
  ('Oleksandr', 'Ivchuk'),
  ('Artiom', 'Borodii'),
  ('Bohdan', 'Chaikovskyi'),
  ('Andrii', 'Regush'),
  ('Bohdan', 'Plakhtyi'),
  ('Mykhailo', 'Potapov'),
  ('Volodymyr', 'Kaidakov'),
  ('Artem', 'Kasyanov'),
  ('Andrii', 'Lushchyk'),
  ('Serhii', 'Semenets'),
  ('Anatolii', 'Kovalenko'),
  ('Mykyta', 'Zinov'),
  ('Ivan', 'Fedoryshyn'),
  ('Maksym', 'Badai'),
  ('Oleksandr', 'Strutinskiy'),
  ('Oleksii', 'Nadporozhskyi'),
  ('Valentyn', 'Chumak'),
  ('Vasyl', 'Moshovskyi'),
  ('Dmytro', 'Kuzmenko'),
  ('Yurii', 'Parahailo'),
  ('Yevhenii', 'Korotin'),
  ('Martin', 'Obraz'),
  ('Dmytro', 'Rehotun'),
  ('Dmytro', 'Derevynskyi'),
  ('Oleh', 'Stopin'),
  ('Stefan', 'Yakimenko'),
  ('Sergii', 'Sideltsev'),
  ('Volodymyr', 'Okopnyi'),
  ('Valerii', 'Kolesnykov'),
  ('Serhii', 'Solomko'),
  ('Roman', 'Horokh'),
  ('Roman', 'Hnoievoi');


-- -------------------------------------------------------------
--  Paires suivies (253)
-- -------------------------------------------------------------
INSERT INTO tracked_pairs (player1_id, player2_id) VALUES
  ((SELECT player_id FROM players WHERE first_name='Orest' AND last_name='Hura'),
   (SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Vlasenko')),
  ((SELECT player_id FROM players WHERE first_name='Orest' AND last_name='Hura'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Napirko')),
  ((SELECT player_id FROM players WHERE first_name='Orest' AND last_name='Hura'),
   (SELECT player_id FROM players WHERE first_name='Mykyta' AND last_name='Smyrnov')),
  ((SELECT player_id FROM players WHERE first_name='Nazarii' AND last_name='Kovalchuk'),
   (SELECT player_id FROM players WHERE first_name='Orest' AND last_name='Hura')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Vlasenko'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Napirko')),
  ((SELECT player_id FROM players WHERE first_name='Nazarii' AND last_name='Kovalchuk'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Napirko')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Napirko'),
   (SELECT player_id FROM players WHERE first_name='Anton' AND last_name='Shypilov')),
  ((SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Reznychenko'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Tuzhylin')),
  ((SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Cherevko'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Tuzhylin')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Melnyk'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Tuzhylin')),
  ((SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Masko'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Tuzhylin')),
  ((SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Pysmennyi'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Tuzhylin')),
  ((SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Pysmennyi'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Cherevko')),
  ((SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Reznychenko'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Cherevko')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Melnyk'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Cherevko')),
  ((SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Pysmennyi'),
   (SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Masko')),
  ((SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Hucko'),
   (SELECT player_id FROM players WHERE first_name='Premysl' AND last_name='Rucky')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Prus'),
   (SELECT player_id FROM players WHERE first_name='Denys' AND last_name='Maltsev')),
  ((SELECT player_id FROM players WHERE first_name='Ivan' AND last_name='Fashchevskyi'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Savenkov')),
  ((SELECT player_id FROM players WHERE first_name='David' AND last_name='Sabuka'),
   (SELECT player_id FROM players WHERE first_name='Karel' AND last_name='Farsky')),
  ((SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Patalakha'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Tymofeev')),
  ((SELECT player_id FROM players WHERE first_name='Evhenii' AND last_name='Hrytsenko'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Kuzyshyn')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Aristarkhov'),
   (SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Tatarnykov')),
  ((SELECT player_id FROM players WHERE first_name='Oleksii' AND last_name='Tiutiunnyk'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Kiilo')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Melnyk'),
   (SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Masko')),
  ((SELECT player_id FROM players WHERE first_name='Denys' AND last_name='Maltsev'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Savenkov')),
  ((SELECT player_id FROM players WHERE first_name='David' AND last_name='Sabuka'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Merkl')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Varlamov'),
   (SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Bilobrov')),
  ((SELECT player_id FROM players WHERE first_name='Bogdan' AND last_name='Panchenko'),
   (SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Prylepa')),
  ((SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Belanchik'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Prus')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Tymofeev'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Dekhtiarenko')),
  ((SELECT player_id FROM players WHERE first_name='Milan' AND last_name='Cuba'),
   (SELECT player_id FROM players WHERE first_name='Martin' AND last_name='Holub')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Zhyrnov'),
   (SELECT player_id FROM players WHERE first_name='Yaroslav' AND last_name='Kovshun')),
  ((SELECT player_id FROM players WHERE first_name='Stepan' AND last_name='Kalensky'),
   (SELECT player_id FROM players WHERE first_name='Marian' AND last_name='Melisek')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Tatarnykov'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Kurylenko')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Kuzyshyn'),
   (SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Bilobrov')),
  ((SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Patalakha'),
   (SELECT player_id FROM players WHERE first_name='Eduard' AND last_name='Populovskyi')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Aristarkhov'),
   (SELECT player_id FROM players WHERE first_name='Bogdan' AND last_name='Panchenko')),
  ((SELECT player_id FROM players WHERE first_name='Yaroslav' AND last_name='Kovshun'),
   (SELECT player_id FROM players WHERE first_name='Evhenii' AND last_name='Hrytsenko')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Tatarnykov'),
   (SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Prylepa')),
  ((SELECT player_id FROM players WHERE first_name='Ivan' AND last_name='Fashchevskyi'),
   (SELECT player_id FROM players WHERE first_name='Denys' AND last_name='Maltsev')),
  ((SELECT player_id FROM players WHERE first_name='Martin' AND last_name='Holub'),
   (SELECT player_id FROM players WHERE first_name='Marcel' AND last_name='Cmil')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Kurylenko'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Aristarkhov')),
  ((SELECT player_id FROM players WHERE first_name='Oleksii' AND last_name='Tiutiunnyk'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Kushnirenko')),
  ((SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Palii'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Prus')),
  ((SELECT player_id FROM players WHERE first_name='Marcel' AND last_name='Cmil'),
   (SELECT player_id FROM players WHERE first_name='Milan' AND last_name='Cuba')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Kiilo'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Kushnirenko')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Melnyk'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Reznychenko')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Prus'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Savenkov')),
  ((SELECT player_id FROM players WHERE first_name='Marcel' AND last_name='Cmil'),
   (SELECT player_id FROM players WHERE first_name='Vaclav' AND last_name='Coubal')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Zhyrnov'),
   (SELECT player_id FROM players WHERE first_name='Evhenii' AND last_name='Hrytsenko')),
  ((SELECT player_id FROM players WHERE first_name='Josef' AND last_name='Chalupa'),
   (SELECT player_id FROM players WHERE first_name='Stepan' AND last_name='Rejent')),
  ((SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Liska'),
   (SELECT player_id FROM players WHERE first_name='Lukas' AND last_name='Rulc')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Zhyrnov'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Kuzyshyn')),
  ((SELECT player_id FROM players WHERE first_name='Vadym' AND last_name='Kucheriavyi'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Kurtenko')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Kurylenko'),
   (SELECT player_id FROM players WHERE first_name='Bogdan' AND last_name='Panchenko')),
  ((SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Skorobahatyi'),
   (SELECT player_id FROM players WHERE first_name='Anatolii' AND last_name='Nazarov')),
  ((SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Liska'),
   (SELECT player_id FROM players WHERE first_name='Josef' AND last_name='Chalupa')),
  ((SELECT player_id FROM players WHERE first_name='Bohdan' AND last_name='Kohut'),
   (SELECT player_id FROM players WHERE first_name='Ivan' AND last_name='Kozachuk')),
  ((SELECT player_id FROM players WHERE first_name='Ihor' AND last_name='Serdiuk'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Boklah')),
  ((SELECT player_id FROM players WHERE first_name='Sergey' AND last_name='Osipov'),
   (SELECT player_id FROM players WHERE first_name='Stanislav' AND last_name='Kucera')),
  ((SELECT player_id FROM players WHERE first_name='Jan' AND last_name='Krojidlo'),
   (SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Chadima')),
  ((SELECT player_id FROM players WHERE first_name='Lukas' AND last_name='Rulc'),
   (SELECT player_id FROM players WHERE first_name='Stepan' AND last_name='Rejent')),
  ((SELECT player_id FROM players WHERE first_name='Yaroslav' AND last_name='Kovshun'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Kuzyshyn')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Bandurka'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Rak')),
  ((SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Chadima'),
   (SELECT player_id FROM players WHERE first_name='Jachym' AND last_name='Juppa')),
  ((SELECT player_id FROM players WHERE first_name='Vitalii' AND last_name='Ananiev'),
   (SELECT player_id FROM players WHERE first_name='Vitalii' AND last_name='Klymenko')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Zhyrnov'),
   (SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Bilobrov')),
  ((SELECT player_id FROM players WHERE first_name='Jan' AND last_name='Krojidlo'),
   (SELECT player_id FROM players WHERE first_name='Radek' AND last_name='Slunecko')),
  ((SELECT player_id FROM players WHERE first_name='Daniil' AND last_name='Yevdokymov'),
   (SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Tkalich')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Danylov'),
   (SELECT player_id FROM players WHERE first_name='Mykola' AND last_name='Pohorilyi')),
  ((SELECT player_id FROM players WHERE first_name='Ivan' AND last_name='Krivoy'),
   (SELECT player_id FROM players WHERE first_name='Mykolay' AND last_name='Treschetka')),
  ((SELECT player_id FROM players WHERE first_name='Kostiantyn' AND last_name='Hrynenko'),
   (SELECT player_id FROM players WHERE first_name='Yan' AND last_name='Krol')),
  ((SELECT player_id FROM players WHERE first_name='Maxim' AND last_name='Marchuk'),
   (SELECT player_id FROM players WHERE first_name='Kostiantyn' AND last_name='Hrynenko')),
  ((SELECT player_id FROM players WHERE first_name='Jan' AND last_name='Krojidlo'),
   (SELECT player_id FROM players WHERE first_name='Jan' AND last_name='Marhol')),
  ((SELECT player_id FROM players WHERE first_name='Radek' AND last_name='Slunecko'),
   (SELECT player_id FROM players WHERE first_name='Karel' AND last_name='Farsky')),
  ((SELECT player_id FROM players WHERE first_name='Jakub' AND last_name='Senk'),
   (SELECT player_id FROM players WHERE first_name='Lukas' AND last_name='Rulc')),
  ((SELECT player_id FROM players WHERE first_name='Michal' AND last_name='Makara'),
   (SELECT player_id FROM players WHERE first_name='Lukas' AND last_name='Rulc')),
  ((SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Liska'),
   (SELECT player_id FROM players WHERE first_name='Michal' AND last_name='Makara')),
  ((SELECT player_id FROM players WHERE first_name='Michal' AND last_name='Makara'),
   (SELECT player_id FROM players WHERE first_name='Jakub' AND last_name='Senk')),
  ((SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Liska'),
   (SELECT player_id FROM players WHERE first_name='Jakub' AND last_name='Senk')),
  ((SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Kovalchuk'),
   (SELECT player_id FROM players WHERE first_name='Yaroslav' AND last_name='Vorsulyak')),
  ((SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Khomenko'),
   (SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Shchegelskyi')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Ivasiv'),
   (SELECT player_id FROM players WHERE first_name='Yaroslav' AND last_name='Vorsulyak')),
  ((SELECT player_id FROM players WHERE first_name='Ivan' AND last_name='Fashchevskyi'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Prus')),
  ((SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Kovalchuk'),
   (SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Khomenko')),
  ((SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Khomenko'),
   (SELECT player_id FROM players WHERE first_name='Yaroslav' AND last_name='Vorsulyak')),
  ((SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Kovalchuk'),
   (SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Shchegelskyi')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Ivasiv'),
   (SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Kovalchuk')),
  ((SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Shchegelskyi'),
   (SELECT player_id FROM players WHERE first_name='Yaroslav' AND last_name='Vorsulyak')),
  ((SELECT player_id FROM players WHERE first_name='Mykola' AND last_name='Kulynych'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Maksymkiv')),
  ((SELECT player_id FROM players WHERE first_name='Mykola' AND last_name='Kulynych'),
   (SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Salivonchyk')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Maslovskyi'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Maksymkiv')),
  ((SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Salivonchyk'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Maksymkiv')),
  ((SELECT player_id FROM players WHERE first_name='Ihor' AND last_name='Serdiuk'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Priadko')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Priadko'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Boklah')),
  ((SELECT player_id FROM players WHERE first_name='Ihor' AND last_name='Serdiuk'),
   (SELECT player_id FROM players WHERE first_name='Ihor' AND last_name='Torhachov')),
  ((SELECT player_id FROM players WHERE first_name='Ihor' AND last_name='Torhachov'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Boklah')),
  ((SELECT player_id FROM players WHERE first_name='Petr' AND last_name='Abraham'),
   (SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Chadima')),
  ((SELECT player_id FROM players WHERE first_name='Martin' AND last_name='Stehlik'),
   (SELECT player_id FROM players WHERE first_name='Viktor' AND last_name='Kucala')),
  ((SELECT player_id FROM players WHERE first_name='Petr' AND last_name='Fiser'),
   (SELECT player_id FROM players WHERE first_name='Stepan' AND last_name='Kalensky')),
  ((SELECT player_id FROM players WHERE first_name='Martin' AND last_name='Stehlik'),
   (SELECT player_id FROM players WHERE first_name='Stepan' AND last_name='Kalensky')),
  ((SELECT player_id FROM players WHERE first_name='Petr' AND last_name='Fiser'),
   (SELECT player_id FROM players WHERE first_name='Viktor' AND last_name='Kucala')),
  ((SELECT player_id FROM players WHERE first_name='Jan' AND last_name='Seeman'),
   (SELECT player_id FROM players WHERE first_name='Josef' AND last_name='Hanacek')),
  ((SELECT player_id FROM players WHERE first_name='Karel' AND last_name='Polak'),
   (SELECT player_id FROM players WHERE first_name='Josef' AND last_name='Hanacek')),
  ((SELECT player_id FROM players WHERE first_name='Jan' AND last_name='Seeman'),
   (SELECT player_id FROM players WHERE first_name='Karel' AND last_name='Polak')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Mishchenko'),
   (SELECT player_id FROM players WHERE first_name='Artem' AND last_name='Chepurnyi')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Chelpanov'),
   (SELECT player_id FROM players WHERE first_name='Artem' AND last_name='Chepurnyi')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Mishchenko'),
   (SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Kryvorotko')),
  ((SELECT player_id FROM players WHERE first_name='Artem' AND last_name='Chepurnyi'),
   (SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Kryvorotko')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Chelpanov'),
   (SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Kryvorotko')),
  ((SELECT player_id FROM players WHERE first_name='Ladislav' AND last_name='Dobias'),
   (SELECT player_id FROM players WHERE first_name='Zdenek' AND last_name='Sedivy')),
  ((SELECT player_id FROM players WHERE first_name='Zdenek' AND last_name='Sedivy'),
   (SELECT player_id FROM players WHERE first_name='Josef' AND last_name='Chalupa')),
  ((SELECT player_id FROM players WHERE first_name='Zdenek' AND last_name='Kuksa'),
   (SELECT player_id FROM players WHERE first_name='Jachym' AND last_name='Juppa')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Maksymkiv'),
   (SELECT player_id FROM players WHERE first_name='Anatolii' AND last_name='Nikolenko')),
  ((SELECT player_id FROM players WHERE first_name='Martin' AND last_name='Stehlik'),
   (SELECT player_id FROM players WHERE first_name='Vaclav' AND last_name='Coubal')),
  ((SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Zholubak'),
   (SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Verbianyi')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Voronenkov'),
   (SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Mrykh')),
  ((SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Hubenko'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Chuhai')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Chuhai'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Vasylets')),
  ((SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Mishchenko'),
   (SELECT player_id FROM players WHERE first_name='Artem' AND last_name='Yurkov')),
  ((SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Mrykh'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Kolbasenko')),
  ((SELECT player_id FROM players WHERE first_name='Mariia' AND last_name='Dotsenko'),
   (SELECT player_id FROM players WHERE first_name='Jan Sr' AND last_name='Krames')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Merzlikin'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Derevianko')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Levytskyi'),
   (SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Novik')),
  ((SELECT player_id FROM players WHERE first_name='Martin' AND last_name='Stehlik'),
   (SELECT player_id FROM players WHERE first_name='Jan' AND last_name='Blazek')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Maksymkiv'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Matveichuk')),
  ((SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Kovalenko'),
   (SELECT player_id FROM players WHERE first_name='Vitalii' AND last_name='Kaganovych')),
  ((SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Matviichuk'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Honcharenko')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Zhyrnov'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Derevianko')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Maksymkiv'),
   (SELECT player_id FROM players WHERE first_name='Viktor' AND last_name='Kodola')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Kolbasenko'),
   (SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Mishchenko')),
  ((SELECT player_id FROM players WHERE first_name='Vadym' AND last_name='Ishchuk'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Derevianko')),
  ((SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Kovalenko'),
   (SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Bielokon')),
  ((SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Chadima'),
   (SELECT player_id FROM players WHERE first_name='Zdenek' AND last_name='Kuksa')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Zhyrnov'),
   (SELECT player_id FROM players WHERE first_name='Vadym' AND last_name='Ishchuk')),
  ((SELECT player_id FROM players WHERE first_name='Viktor' AND last_name='Sharpai'),
   (SELECT player_id FROM players WHERE first_name='Yaroslav' AND last_name='Stepanchuk')),
  ((SELECT player_id FROM players WHERE first_name='Viktor' AND last_name='Sharpai'),
   (SELECT player_id FROM players WHERE first_name='Mykola' AND last_name='Polysynskyi')),
  ((SELECT player_id FROM players WHERE first_name='Anton' AND last_name='Shypilov'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Kalenyk')),
  ((SELECT player_id FROM players WHERE first_name='Mykola' AND last_name='Polysynskyi'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Khandetskyi')),
  ((SELECT player_id FROM players WHERE first_name='Mykola' AND last_name='Kulynych'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Matveichuk')),
  ((SELECT player_id FROM players WHERE first_name='Nazar' AND last_name='Danyliuk'),
   (SELECT player_id FROM players WHERE first_name='Vadym' AND last_name='Hryban')),
  ((SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Stukalov'),
   (SELECT player_id FROM players WHERE first_name='Vitalii' AND last_name='Korniichuk')),
  ((SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Prylepa'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Kurylenko')),
  ((SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Troian'),
   (SELECT player_id FROM players WHERE first_name='Evhenii' AND last_name='Holoborodko')),
  ((SELECT player_id FROM players WHERE first_name='Pavel' AND last_name='Sourek'),
   (SELECT player_id FROM players WHERE first_name='Filip' AND last_name='Vesely')),
  ((SELECT player_id FROM players WHERE first_name='Hryhorii' AND last_name='Prokopenko'),
   (SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Matviichuk')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Volynets'),
   (SELECT player_id FROM players WHERE first_name='Yurii' AND last_name='Volkov')),
  ((SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Mezera'),
   (SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Hucko')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Savoliuk'),
   (SELECT player_id FROM players WHERE first_name='Daniil' AND last_name='Habrelyan')),
  ((SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Sveshnykov'),
   (SELECT player_id FROM players WHERE first_name='Viktor' AND last_name='Hyriavyi')),
  ((SELECT player_id FROM players WHERE first_name='Nazar' AND last_name='Danyliuk'),
   (SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Verbianyi')),
  ((SELECT player_id FROM players WHERE first_name='Pavel' AND last_name='Sourek'),
   (SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Hucko')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Syksa'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Chuhai')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Badanin'),
   (SELECT player_id FROM players WHERE first_name='Hryhorii' AND last_name='Prokopenko')),
  ((SELECT player_id FROM players WHERE first_name='Martin' AND last_name='Vorel'),
   (SELECT player_id FROM players WHERE first_name='Josef' AND last_name='Hondlik')),
  ((SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Mezera'),
   (SELECT player_id FROM players WHERE first_name='Filip' AND last_name='Vesely')),
  ((SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Sveshnykov'),
   (SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Matviichuk')),
  ((SELECT player_id FROM players WHERE first_name='Orest' AND last_name='Hura'),
   (SELECT player_id FROM players WHERE first_name='Anton' AND last_name='Shypilov')),
  ((SELECT player_id FROM players WHERE first_name='Pavel' AND last_name='Sourek'),
   (SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Mezera')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Savoliuk'),
   (SELECT player_id FROM players WHERE first_name='Vadym' AND last_name='Ishchuk')),
  ((SELECT player_id FROM players WHERE first_name='Hryhorii' AND last_name='Prokopenko'),
   (SELECT player_id FROM players WHERE first_name='Viktor' AND last_name='Hyriavyi')),
  ((SELECT player_id FROM players WHERE first_name='Martin' AND last_name='Vorel'),
   (SELECT player_id FROM players WHERE first_name='Ladislav' AND last_name='Hendrych')),
  ((SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Hucko'),
   (SELECT player_id FROM players WHERE first_name='Filip' AND last_name='Vesely')),
  ((SELECT player_id FROM players WHERE first_name='Anatolii' AND last_name='Nazarov'),
   (SELECT player_id FROM players WHERE first_name='Daniil' AND last_name='Habrelyan')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Badanin'),
   (SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Matviichuk')),
  ((SELECT player_id FROM players WHERE first_name='Anton' AND last_name='Molochko'),
   (SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Verbianyi')),
  ((SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Troian'),
   (SELECT player_id FROM players WHERE first_name='Arsenii' AND last_name='Lobanov')),
  ((SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Matveichuk'),
   (SELECT player_id FROM players WHERE first_name='Viktor' AND last_name='Kodola')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Chuhai'),
   (SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Prylepa')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Shyshman'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Volynets')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Vlasenko'),
   (SELECT player_id FROM players WHERE first_name='Anton' AND last_name='Shypilov')),
  ((SELECT player_id FROM players WHERE first_name='Vitalii' AND last_name='Korniichuk'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Miklukha')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Kurylenko'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Chuhai')),
  ((SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Verbianyi'),
   (SELECT player_id FROM players WHERE first_name='Vadym' AND last_name='Hryban')),
  ((SELECT player_id FROM players WHERE first_name='Yurii' AND last_name='Volkov'),
   (SELECT player_id FROM players WHERE first_name='Arsenii' AND last_name='Lobanov')),
  ((SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Karpisek'),
   (SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Chadima')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Savoliuk'),
   (SELECT player_id FROM players WHERE first_name='Yevhen' AND last_name='Skorobahatyi')),
  ((SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Studinikin'),
   (SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Stukalov')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Volynets'),
   (SELECT player_id FROM players WHERE first_name='Evhenii' AND last_name='Holoborodko')),
  ((SELECT player_id FROM players WHERE first_name='Vsevolod' AND last_name='Kheresko'),
   (SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Matveichuk')),
  ((SELECT player_id FROM players WHERE first_name='Anton' AND last_name='Molochko'),
   (SELECT player_id FROM players WHERE first_name='Vadym' AND last_name='Hryban')),
  ((SELECT player_id FROM players WHERE first_name='Zdenek' AND last_name='Kuksa'),
   (SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Karpisek')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Varlamov'),
   (SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Merzlikin')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Vlasenko'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Kalenyk')),
  ((SELECT player_id FROM players WHERE first_name='Nazarii' AND last_name='Kovalchuk'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Kalenyk')),
  ((SELECT player_id FROM players WHERE first_name='Anton' AND last_name='Shypilov'),
   (SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Dobrovolskyi')),
  ((SELECT player_id FROM players WHERE first_name='Nazarii' AND last_name='Kovalchuk'),
   (SELECT player_id FROM players WHERE first_name='Anton' AND last_name='Shypilov')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Vlasenko'),
   (SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Dobrovolskyi')),
  ((SELECT player_id FROM players WHERE first_name='Nazarii' AND last_name='Kovalchuk'),
   (SELECT player_id FROM players WHERE first_name='Mykyta' AND last_name='Smyrnov')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Vlasenko'),
   (SELECT player_id FROM players WHERE first_name='Nazarii' AND last_name='Kovalchuk')),
  ((SELECT player_id FROM players WHERE first_name='Mykyta' AND last_name='Smyrnov'),
   (SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Dobrovolskyi')),
  ((SELECT player_id FROM players WHERE first_name='Vitalii' AND last_name='Ananiev'),
   (SELECT player_id FROM players WHERE first_name='Denys' AND last_name='Kozoriz')),
  ((SELECT player_id FROM players WHERE first_name='Viktor' AND last_name='Sharpai'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Homylko')),
  ((SELECT player_id FROM players WHERE first_name='Ludek' AND last_name='Stoces'),
   (SELECT player_id FROM players WHERE first_name='Martin' AND last_name='Skyba')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Dobrovolskyi'),
   (SELECT player_id FROM players WHERE first_name='Denys' AND last_name='Kozoriz')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Mytsyk'),
   (SELECT player_id FROM players WHERE first_name='Eduard' AND last_name='Populovskyi')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Kryvoshyi'),
   (SELECT player_id FROM players WHERE first_name='Denys' AND last_name='Kozoriz')),
  ((SELECT player_id FROM players WHERE first_name='Yaroslav' AND last_name='Kovshun'),
   (SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Merzlikin')),
  ((SELECT player_id FROM players WHERE first_name='Radovan' AND last_name='Pisa'),
   (SELECT player_id FROM players WHERE first_name='Jan Sr' AND last_name='Krames')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Mytsyk'),
   (SELECT player_id FROM players WHERE first_name='Sergii' AND last_name='Skhabitskiy')),
  ((SELECT player_id FROM players WHERE first_name='Milan' AND last_name='Cuba'),
   (SELECT player_id FROM players WHERE first_name='Artur' AND last_name='Akopyan')),
  ((SELECT player_id FROM players WHERE first_name='Jan Sr' AND last_name='Krames'),
   (SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Liska')),
  ((SELECT player_id FROM players WHERE first_name='Jaroslav' AND last_name='Puk'),
   (SELECT player_id FROM players WHERE first_name='Zdenek' AND last_name='Kuksa')),
  ((SELECT player_id FROM players WHERE first_name='Petr' AND last_name='Kotrbacek'),
   (SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Plyska')),
  ((SELECT player_id FROM players WHERE first_name='Jaroslav' AND last_name='Puk'),
   (SELECT player_id FROM players WHERE first_name='Petr' AND last_name='Kotrbacek')),
  ((SELECT player_id FROM players WHERE first_name='Dominik' AND last_name='Horak'),
   (SELECT player_id FROM players WHERE first_name='Pavel' AND last_name='Fencl')),
  ((SELECT player_id FROM players WHERE first_name='Marek' AND last_name='Vyskocil'),
   (SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Mezera')),
  ((SELECT player_id FROM players WHERE first_name='Ondrej' AND last_name='Mezera'),
   (SELECT player_id FROM players WHERE first_name='Dominik' AND last_name='Horak')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Syksa'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Ziakun')),
  ((SELECT player_id FROM players WHERE first_name='Vihen' AND last_name='Saakian'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Honcharenko')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Merzlikin'),
   (SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Tiutiunnyk')),
  ((SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Studinikin'),
   (SELECT player_id FROM players WHERE first_name='Ihor' AND last_name='Burak')),
  ((SELECT player_id FROM players WHERE first_name='Yurii' AND last_name='Zvolynskyi'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Honcharenko')),
  ((SELECT player_id FROM players WHERE first_name='Yaroslav' AND last_name='Kovshun'),
   (SELECT player_id FROM players WHERE first_name='Daniil' AND last_name='Habrelyan')),
  ((SELECT player_id FROM players WHERE first_name='Ivan' AND last_name='Nitchenko'),
   (SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Merzlikin')),
  ((SELECT player_id FROM players WHERE first_name='Andriy' AND last_name='Didyk'),
   (SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Dobrovolskyi')),
  ((SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Kotiash'),
   (SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Kondratenko')),
  ((SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Mazur'),
   (SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Kryvoshyi')),
  ((SELECT player_id FROM players WHERE first_name='Eduard' AND last_name='Populovskyi'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Lipeiko')),
  ((SELECT player_id FROM players WHERE first_name='Oleh' AND last_name='Miklukha'),
   (SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Studinikin')),
  ((SELECT player_id FROM players WHERE first_name='Evhenii' AND last_name='Hrytsenko'),
   (SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Tiutiunnyk')),
  ((SELECT player_id FROM players WHERE first_name='Vladimir' AND last_name='Lopata'),
   (SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Hanke')),
  ((SELECT player_id FROM players WHERE first_name='David' AND last_name='Sabuka'),
   (SELECT player_id FROM players WHERE first_name='Vladimir' AND last_name='Lopata')),
  ((SELECT player_id FROM players WHERE first_name='Marek' AND last_name='Cizek'),
   (SELECT player_id FROM players WHERE first_name='Tomas' AND last_name='Hanke')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Kolbasenko'),
   (SELECT player_id FROM players WHERE first_name='Pavlo' AND last_name='Babenko')),
  ((SELECT player_id FROM players WHERE first_name='Pavlo' AND last_name='Babenko'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Ivchuk')),
  ((SELECT player_id FROM players WHERE first_name='Artem' AND last_name='Yurkov'),
   (SELECT player_id FROM players WHERE first_name='Pavlo' AND last_name='Babenko')),
  ((SELECT player_id FROM players WHERE first_name='Bohdan' AND last_name='Chaikovskyi'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Regush')),
  ((SELECT player_id FROM players WHERE first_name='Artiom' AND last_name='Borodii'),
   (SELECT player_id FROM players WHERE first_name='Bohdan' AND last_name='Plakhtyi')),
  ((SELECT player_id FROM players WHERE first_name='Mykhailo' AND last_name='Potapov'),
   (SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Shchegelskyi')),
  ((SELECT player_id FROM players WHERE first_name='Vladyslav' AND last_name='Kovalchuk'),
   (SELECT player_id FROM players WHERE first_name='Mykhailo' AND last_name='Potapov')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Kaidakov'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Regush')),
  ((SELECT player_id FROM players WHERE first_name='Artem' AND last_name='Kasyanov'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Lushchyk')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Semenets'),
   (SELECT player_id FROM players WHERE first_name='Anatolii' AND last_name='Kovalenko')),
  ((SELECT player_id FROM players WHERE first_name='Mykyta' AND last_name='Zinov'),
   (SELECT player_id FROM players WHERE first_name='Anatolii' AND last_name='Nazarov')),
  ((SELECT player_id FROM players WHERE first_name='Ivan' AND last_name='Fedoryshyn'),
   (SELECT player_id FROM players WHERE first_name='Maksym' AND last_name='Badai')),
  ((SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Strutinskiy'),
   (SELECT player_id FROM players WHERE first_name='Oleksii' AND last_name='Nadporozhskyi')),
  ((SELECT player_id FROM players WHERE first_name='Stepan' AND last_name='Rejent'),
   (SELECT player_id FROM players WHERE first_name='Jan Sr' AND last_name='Krames')),
  ((SELECT player_id FROM players WHERE first_name='Valentyn' AND last_name='Chumak'),
   (SELECT player_id FROM players WHERE first_name='Vitalii' AND last_name='Kaganovych')),
  ((SELECT player_id FROM players WHERE first_name='Vasyl' AND last_name='Moshovskyi'),
   (SELECT player_id FROM players WHERE first_name='Denys' AND last_name='Maltsev')),
  ((SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Prylepa'),
   (SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Kuzmenko')),
  ((SELECT player_id FROM players WHERE first_name='Mykhailo' AND last_name='Potapov'),
   (SELECT player_id FROM players WHERE first_name='Yurii' AND last_name='Parahailo')),
  ((SELECT player_id FROM players WHERE first_name='Martin' AND last_name='Obraz'),
   (SELECT player_id FROM players WHERE first_name='Marian' AND last_name='Melisek')),
  ((SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Rehotun'),
   (SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Derevynskyi')),
  ((SELECT player_id FROM players WHERE first_name='Stefan' AND last_name='Yakimenko'),
   (SELECT player_id FROM players WHERE first_name='Anatolii' AND last_name='Kovalenko')),
  ((SELECT player_id FROM players WHERE first_name='Yurii' AND last_name='Zvolynskyi'),
   (SELECT player_id FROM players WHERE first_name='Sergii' AND last_name='Sideltsev')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Okopnyi'),
   (SELECT player_id FROM players WHERE first_name='Andrii' AND last_name='Regush')),
  ((SELECT player_id FROM players WHERE first_name='Valerii' AND last_name='Kolesnykov'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Lipeiko')),
  ((SELECT player_id FROM players WHERE first_name='Serhii' AND last_name='Solomko'),
   (SELECT player_id FROM players WHERE first_name='Stefan' AND last_name='Yakimenko')),
  ((SELECT player_id FROM players WHERE first_name='Volodymyr' AND last_name='Okopnyi'),
   (SELECT player_id FROM players WHERE first_name='Bohdan' AND last_name='Chaikovskyi')),
  ((SELECT player_id FROM players WHERE first_name='Mykyta' AND last_name='Zinov'),
   (SELECT player_id FROM players WHERE first_name='Oleksandr' AND last_name='Strutinskiy')),
  ((SELECT player_id FROM players WHERE first_name='Roman' AND last_name='Hnoievoi'),
   (SELECT player_id FROM players WHERE first_name='Dmytro' AND last_name='Shchegelskyi'));
